### ISSUE TITLE
Login return

### ISSUE THREAD

**Issue by MattBurseth1221** [oph0109/ticketing-system#7]
@oph0109 When I supply invalid credentials I get JSON error back - can't tell if it's on my end or not - can you return an error object like you do when a user tries creating a new user with existing credentials?

**Comment by MattBurseth1221** [comment]
IMPORTANT this is on frontend branch btw

**Comment by MattBurseth1221** [comment]
Shits fucked

**Comment by oph0109** [comment]
> Shits fucked

No moree swearing dude
